exports.egSentenceString1 = "kobieta jest *bardzo czerwona";

exports.egSentenceStructure1 = [
  {
    structureChunk: {
      person: {
        isLexical: true,
        compatibleWordtypes: ["nounPerson", "nounCommon", "verb", "pronombre"],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["1per", "2per", "3per", "impersonal"],
      },
      gender: {
        isLexical: true,
        compatibleWordtypes: [
          "nounPerson",
          "nounCommon",
          "verb",
          "adjective",
          "pronombre",
        ],
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "m",
          "m1",
          "m2",
          "m3",
          "f",
          "n",
          "virile",
          "nonvirile",
        ],
      },
      number: {
        isLexical: true,
        compatibleWordtypes: [
          "nounPerson",
          "nounCommon",
          "verb",
          "adjective",
          "pronombre",
        ],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["singular", "plural"],
        traitValue: ["singular", "plural"],
      },
      gcase: {
        isLexical: true,
        compatibleWordtypes: [
          "nounPerson",
          "nounCommon",
          "adjective",
          "pronombre",
        ],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["nom", "gen", "dat", "acc", "ins", "loc"],
      },
      educatorBlocksAnnotationsForTheseTraitKeys: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      formulaImportantTraitKeys: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      blockedLemmaObjectTypes: {
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["tantumPlurale", "tantumSingulare"],
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      specificIds: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        traitValue: ["^pol-npe-011-kobieta"],
      },
      andTags: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        traitValue: ["personTest1"],
      },
      orTags: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
      },
      chunkId: {
        expectedTypeOnStCh: "string",
        traitValue: "npe-1-kobieta",
      },
      merelyPreferredChoicesForQuestionSentence: {
        expectedTypeOnStCh: "array",
      },
      agreeWith: {
        expectedTypeOnStCh: "string",
        mustBeExistingChunkId: true,
      },
      giveMeTheseClarifiersOfMyHeadChunk: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        possibleTraitValues: [
          "number",
          "gender",
          "gcase",
          "form",
          "person",
          "aspect",
          "tense",
          "tenseDescription",
        ],
      },
      booleanTraits: {
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "preventAddingFurtherClarifiers",
          "pleaseShowMultipleWordtypeAllohomClarifiers",
          "doNotUpdateSpecificIdsAsIsJustOneMGN",
          "dontSpecifyOnThisChunk",
        ],
        traitValue: [],
      },
    },
    backedUpStructureChunk: {
      person: {
        isLexical: true,
        compatibleWordtypes: ["nounPerson", "nounCommon", "verb", "pronombre"],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["1per", "2per", "3per", "impersonal"],
      },
      gender: {
        isLexical: true,
        compatibleWordtypes: [
          "nounPerson",
          "nounCommon",
          "verb",
          "adjective",
          "pronombre",
        ],
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "m",
          "m1",
          "m2",
          "m3",
          "f",
          "n",
          "virile",
          "nonvirile",
        ],
      },
      number: {
        isLexical: true,
        compatibleWordtypes: [
          "nounPerson",
          "nounCommon",
          "verb",
          "adjective",
          "pronombre",
        ],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["singular", "plural"],
        traitValue: ["singular", "plural"],
      },
      gcase: {
        isLexical: true,
        compatibleWordtypes: [
          "nounPerson",
          "nounCommon",
          "adjective",
          "pronombre",
        ],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["nom", "gen", "dat", "acc", "ins", "loc"],
      },
      educatorBlocksAnnotationsForTheseTraitKeys: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      formulaImportantTraitKeys: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      blockedLemmaObjectTypes: {
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["tantumPlurale", "tantumSingulare"],
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      specificIds: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        traitValue: ["^pol-npe-011-kobieta"],
      },
      andTags: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        traitValue: ["personTest1"],
      },
      orTags: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
      },
      chunkId: {
        expectedTypeOnStCh: "string",
        traitValue: "npe-1-kobieta",
      },
      merelyPreferredChoicesForQuestionSentence: {
        expectedTypeOnStCh: "array",
      },
      agreeWith: {
        expectedTypeOnStCh: "string",
        mustBeExistingChunkId: true,
      },
      giveMeTheseClarifiersOfMyHeadChunk: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        possibleTraitValues: [
          "number",
          "gender",
          "gcase",
          "form",
          "person",
          "aspect",
          "tense",
          "tenseDescription",
        ],
      },
      booleanTraits: {
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "preventAddingFurtherClarifiers",
          "pleaseShowMultipleWordtypeAllohomClarifiers",
          "doNotUpdateSpecificIdsAsIsJustOneMGN",
          "dontSpecifyOnThisChunk",
        ],
        traitValue: [],
      },
    },
    formulaItemId: "3943754949",
    guideword: "kobieta",
  },
  {
    structureChunk: {
      form: {
        expectedTypeOnStCh: "array",
        isLexical: true,
        compatibleWordtypes: ["adjective", "pronombre", "verb", "preposition"],
        possibleTraitValuesPerWordtype: {
          adjective: ["simple", "comparative", "superlative", "adverb"],
          pronombre: ["pronombre", "_pronombreAndDeterminer", "determiner"],
          verb: [
            "verbal",
            "infinitive",
            "contemporaryAdverbial",
            "passiveAdjectival",
            "activeAdjectival",
            "anteriorAdverbial",
            "verbalNoun",
          ],
          preposition: ["onlyForm"],
        },
        possibleTraitValues: [
          "verbal",
          "infinitive",
          "contemporaryAdverbial",
          "passiveAdjectival",
          "activeAdjectival",
          "anteriorAdverbial",
          "verbalNoun",
        ],
      },
      tenseDescription: {
        isLexical: true,
        compatibleWordtypes: ["verb"],
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "past im",
          "present im",
          "future im",
          "past pf",
          "future pf",
        ],
        traitValue: ["present im"],
      },
      blockedTenseDescriptions: {
        expectedTypeOnStCh: "array",
        compatibleWordtypes: ["verb"],
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
        possibleTraitValues: [
          "past im",
          "present im",
          "future im",
          "past pf",
          "future pf",
        ],
      },
      person: {
        isLexical: true,
        compatibleWordtypes: ["nounPerson", "nounCommon", "verb", "pronombre"],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["1per", "2per", "3per", "impersonal"],
        traitValue: ["3per"],
      },
      gender: {
        isLexical: true,
        compatibleWordtypes: [
          "nounPerson",
          "nounCommon",
          "verb",
          "adjective",
          "pronombre",
        ],
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "m",
          "m1",
          "m2",
          "m3",
          "f",
          "n",
          "virile",
          "nonvirile",
        ],
      },
      number: {
        isLexical: true,
        compatibleWordtypes: [
          "nounPerson",
          "nounCommon",
          "verb",
          "adjective",
          "pronombre",
        ],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["singular", "plural"],
      },
      aspect: {
        isLexical: true,
        compatibleWordtypes: ["verb"],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["imperfective", "perfective", "_imOnly"],
      },
      tense: {
        isLexical: true,
        compatibleWordtypes: ["verb"],
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "past",
          "present",
          "future",
          "conditional",
          "imperative",
        ],
      },
      educatorBlocksAnnotationsForTheseTraitKeys: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      formulaImportantTraitKeys: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      blockedLemmaObjectTypes: {
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["tantumPlurale", "tantumSingulare"],
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      specificIds: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
      },
      andTags: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        traitValue: ["basic2"],
      },
      orTags: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
      },
      chunkId: {
        expectedTypeOnStCh: "string",
        traitValue: "ver-1-czyta",
      },
      merelyPreferredChoicesForQuestionSentence: {
        expectedTypeOnStCh: "array",
      },
      agreeWith: {
        expectedTypeOnStCh: "string",
        mustBeExistingChunkId: true,
        traitValue: "npe-1-kobieta",
      },
      giveMeTheseClarifiersOfMyHeadChunk: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        possibleTraitValues: [
          "number",
          "gender",
          "gcase",
          "form",
          "person",
          "aspect",
          "tense",
          "tenseDescription",
        ],
      },
      booleanTraits: {
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "preventAddingFurtherClarifiers",
          "pleaseShowMultipleWordtypeAllohomClarifiers",
          "doNotUpdateSpecificIdsAsIsJustOneMGN",
          "dontSpecifyOnThisChunk",
        ],
        traitValue: [],
      },
    },
    backedUpStructureChunk: {
      form: {
        expectedTypeOnStCh: "array",
        isLexical: true,
        compatibleWordtypes: ["adjective", "pronombre", "verb", "preposition"],
        possibleTraitValuesPerWordtype: {
          adjective: ["simple", "comparative", "superlative", "adverb"],
          pronombre: ["pronombre", "_pronombreAndDeterminer", "determiner"],
          verb: [
            "verbal",
            "infinitive",
            "contemporaryAdverbial",
            "passiveAdjectival",
            "activeAdjectival",
            "anteriorAdverbial",
            "verbalNoun",
          ],
          preposition: ["onlyForm"],
        },
        possibleTraitValues: [
          "verbal",
          "infinitive",
          "contemporaryAdverbial",
          "passiveAdjectival",
          "activeAdjectival",
          "anteriorAdverbial",
          "verbalNoun",
        ],
      },
      tenseDescription: {
        isLexical: true,
        compatibleWordtypes: ["verb"],
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "past im",
          "present im",
          "future im",
          "past pf",
          "future pf",
        ],
        traitValue: ["present im"],
      },
      blockedTenseDescriptions: {
        expectedTypeOnStCh: "array",
        compatibleWordtypes: ["verb"],
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
        possibleTraitValues: [
          "past im",
          "present im",
          "future im",
          "past pf",
          "future pf",
        ],
      },
      person: {
        isLexical: true,
        compatibleWordtypes: ["nounPerson", "nounCommon", "verb", "pronombre"],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["1per", "2per", "3per", "impersonal"],
        traitValue: ["3per"],
      },
      gender: {
        isLexical: true,
        compatibleWordtypes: [
          "nounPerson",
          "nounCommon",
          "verb",
          "adjective",
          "pronombre",
        ],
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "m",
          "m1",
          "m2",
          "m3",
          "f",
          "n",
          "virile",
          "nonvirile",
        ],
      },
      number: {
        isLexical: true,
        compatibleWordtypes: [
          "nounPerson",
          "nounCommon",
          "verb",
          "adjective",
          "pronombre",
        ],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["singular", "plural"],
      },
      aspect: {
        isLexical: true,
        compatibleWordtypes: ["verb"],
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["imperfective", "perfective", "_imOnly"],
      },
      tense: {
        isLexical: true,
        compatibleWordtypes: ["verb"],
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "past",
          "present",
          "future",
          "conditional",
          "imperative",
        ],
      },
      educatorBlocksAnnotationsForTheseTraitKeys: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      formulaImportantTraitKeys: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      blockedLemmaObjectTypes: {
        expectedTypeOnStCh: "array",
        possibleTraitValues: ["tantumPlurale", "tantumSingulare"],
        ultimatelyMultipleTraitValuesOkay: true,
        needsNoValidation: true,
      },
      specificIds: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
      },
      andTags: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        traitValue: ["basic2"],
      },
      orTags: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
      },
      chunkId: {
        expectedTypeOnStCh: "string",
        traitValue: "ver-1-czyta",
      },
      merelyPreferredChoicesForQuestionSentence: {
        expectedTypeOnStCh: "array",
      },
      agreeWith: {
        expectedTypeOnStCh: "string",
        mustBeExistingChunkId: true,
        traitValue: "npe-1-kobieta",
      },
      giveMeTheseClarifiersOfMyHeadChunk: {
        expectedTypeOnStCh: "array",
        ultimatelyMultipleTraitValuesOkay: true,
        possibleTraitValues: [
          "number",
          "gender",
          "gcase",
          "form",
          "person",
          "aspect",
          "tense",
          "tenseDescription",
        ],
      },
      booleanTraits: {
        expectedTypeOnStCh: "array",
        possibleTraitValues: [
          "preventAddingFurtherClarifiers",
          "pleaseShowMultipleWordtypeAllohomClarifiers",
          "doNotUpdateSpecificIdsAsIsJustOneMGN",
          "dontSpecifyOnThisChunk",
        ],
        traitValue: [],
      },
    },
    formulaItemId: "2801376704",
    guideword: "czyta",
  },
];

exports.testStChs = {
  npeStCh: {
    postHocAgreeWithPrimary: {
      expectedTypeOnStCh: "string",
      mustBeExistingChunkId: true,
    },
    postHocAgreeWithSecondary: {
      expectedTypeOnStCh: "string",
      mustBeExistingChunkId: true,
    },
    postHocAgreeWithTertiary: {
      expectedTypeOnStCh: "string",
      mustBeExistingChunkId: true,
    },
    person: {
      isLexical: true,
      compatibleWordtypes: ["nounPerson", "nounCommon", "verb", "pronombre"],
      expectedTypeOnStCh: "array",
      traitValue: [],
      possibleTraitValues: ["1per", "2per", "3per", "impersonal"],
    },
    gender: {
      traitValue: ["f"],
      isLexical: true,
      compatibleWordtypes: [
        "nounPerson",
        "nounCommon",
        "verb",
        "adjective",
        "pronombre",
      ],
      expectedTypeOnStCh: "array",
      possibleTraitValues: [
        "m",
        "m1",
        "m2",
        "m3",
        "f",
        "n",
        "virile",
        "nonvirile",
      ],
    },
    number: {
      isLexical: true,
      compatibleWordtypes: [
        "nounPerson",
        "nounCommon",
        "verb",
        "adjective",
        "pronombre",
      ],
      expectedTypeOnStCh: "array",
      possibleTraitValues: ["singular", "plural"],
      traitValue: ["singular"],
    },
    gcase: {
      isLexical: true,
      compatibleWordtypes: [
        "nounPerson",
        "nounCommon",
        "adjective",
        "pronombre",
      ],
      expectedTypeOnStCh: "array",
      possibleTraitValues: ["nom", "gen", "dat", "acc", "ins", "loc"],
      traitValue: ["nom"],
    },
    preventAddingFurtherClarifiers: {
      expectedTypeOnStCh: "boolean",
    },
    pleaseShowMultipleWordtypeAllohomClarifiers: {
      expectedTypeOnStCh: "boolean",
      needsNoValidation: true,
    },
    educatorBlocksAnnotationsForTheseTraitKeys: {
      expectedTypeOnStCh: "array",
      traitValue: [],
      ultimatelyMultipleTraitValuesOkay: true,
      needsNoValidation: true,
    },
    formulaImportantTraitKeys: {
      expectedTypeOnStCh: "array",
      traitValue: [],
      ultimatelyMultipleTraitValuesOkay: true,
      needsNoValidation: true,
    },
    blockedTenseDescriptions: {
      expectedTypeOnStCh: "array",
      traitValue: [],
      ultimatelyMultipleTraitValuesOkay: true,
      needsNoValidation: true,
    },
    blockedLemmaObjects: {
      expectedTypeOnStCh: "array",
      traitValue: [],
      ultimatelyMultipleTraitValuesOkay: true,
      needsNoValidation: true,
    },
    hiddenTraits: {
      expectedTypeOnStCh: "array",
      traitValue: [],
      ultimatelyMultipleTraitValuesOkay: true,
      needsNoValidation: true,
    },
    traitsToForceOntoAnswer: {
      expectedTypeOnStCh: "keyValueObject",
      needsNoValidation: true,
    },
    doNotUpdateSpecificLemmasAsIsJustOneMDN: {
      expectedTypeOnStCh: "boolean",
      needsNoValidation: true,
    },

    dontSpecifyOnThisChunk: {
      expectedTypeOnStCh: "boolean",
    },
    specificLemmas: {
      expectedTypeOnStCh: "array",
      traitValue: [],
      ultimatelyMultipleTraitValuesOkay: true,
    },
    specificIds: {
      expectedTypeOnStCh: "array",
      traitValue: [],
      ultimatelyMultipleTraitValuesOkay: true,
    },
    andTags: {
      expectedTypeOnStCh: "array",
      ultimatelyMultipleTraitValuesOkay: true,
      traitValue: ["animate", "personTest1", "concrete"],
    },
    orTags: {
      expectedTypeOnStCh: "array",
      traitValue: ["pet"],
      ultimatelyMultipleTraitValuesOkay: true,
    },
    form: {
      expectedTypeOnStCh: "array",
      traitValue: [],
      isLexical: true,
    },
    chunkId: {
      expectedTypeOnStCh: "string",
    },
    merelyPreferredChoicesForQuestionSentence: {
      expectedTypeOnStCh: "array",
    },
    agreeWith: {
      expectedTypeOnStCh: "string",
      mustBeExistingChunkId: true,
    },
    connectedTo: {
      expectedTypeOnStCh: "string",
      mustBeExistingChunkId: true,
    },
  },
  adjStCh: {
    form: {
      expectedTypeOnStCh: "array",
      isLexical: true,
      compatibleWordtypes: ["adjective", "pronombre", "verb", "preposition"],
      possibleTraitValuesPerWordtype: {
        adjective: ["simple", "comparative", "superlative", "adverb"],
        pronombre: ["pronombre", "pronombreAndDeterminer"],
        verb: [
          "verbal",
          "infinitive",
          "contemporaryAdverbial",
          "passiveAdjectival",
          "activeAdjectival",
          "anteriorAdverbial",
          "verbalNoun",
        ],
        preposition: ["onlyForm"],
      },
      possibleTraitValues: ["simple", "comparative", "superlative", "adverb"],
      traitValue: ["simple"],
    },
    postHocAgreeWithPrimary: {
      expectedTypeOnStCh: "string",
      mustBeExistingChunkId: true,
    },
    postHocAgreeWithSecondary: {
      expectedTypeOnStCh: "string",
      mustBeExistingChunkId: true,
    },
    postHocAgreeWithTertiary: {
      expectedTypeOnStCh: "string",
      mustBeExistingChunkId: true,
    },
    gender: {
      isLexical: true,
      compatibleWordtypes: [
        "nounPerson",
        "nounCommon",
        "verb",
        "adjective",
        "pronombre",
      ],
      expectedTypeOnStCh: "array",
      possibleTraitValues: [
        "m",
        "m1",
        "m2",
        "m3",
        "f",
        "n",
        "virile",
        "nonvirile",
      ],
      traitValue: ["m3"],
    },
    number: {
      isLexical: true,
      compatibleWordtypes: [
        "nounPerson",
        "nounCommon",
        "verb",
        "adjective",
        "pronombre",
      ],
      expectedTypeOnStCh: "array",
      possibleTraitValues: ["singular", "plural"],
      traitValue: ["singular"],
    },
    gcase: {
      isLexical: true,
      compatibleWordtypes: [
        "nounPerson",
        "nounCommon",
        "adjective",
        "pronombre",
      ],
      expectedTypeOnStCh: "array",
      possibleTraitValues: ["nom", "gen", "dat", "acc", "ins", "loc"],
      traitValue: ["acc"],
    },
    preventAddingFurtherClarifiers: {
      expectedTypeOnStCh: "boolean",
    },
    pleaseShowMultipleWordtypeAllohomClarifiers: {
      expectedTypeOnStCh: "boolean",
      needsNoValidation: true,
    },
    educatorBlocksAnnotationsForTheseTraitKeys: {
      expectedTypeOnStCh: "array",
      ultimatelyMultipleTraitValuesOkay: true,
      needsNoValidation: true,
      traitValue: [],
    },
    formulaImportantTraitKeys: {
      expectedTypeOnStCh: "array",
      ultimatelyMultipleTraitValuesOkay: true,
      needsNoValidation: true,
      traitValue: [],
    },
    blockedTenseDescriptions: {
      expectedTypeOnStCh: "array",
      ultimatelyMultipleTraitValuesOkay: true,
      needsNoValidation: true,
      traitValue: [],
    },
    blockedLemmaObjects: {
      expectedTypeOnStCh: "array",
      ultimatelyMultipleTraitValuesOkay: true,
      needsNoValidation: true,
      traitValue: [],
    },
    hiddenTraits: {
      expectedTypeOnStCh: "array",
      ultimatelyMultipleTraitValuesOkay: true,
      needsNoValidation: true,
      traitValue: [],
    },
    traitsToForceOntoAnswer: {
      expectedTypeOnStCh: "keyValueObject",
      needsNoValidation: true,
    },
    doNotUpdateSpecificLemmasAsIsJustOneMDN: {
      expectedTypeOnStCh: "boolean",
      needsNoValidation: true,
    },

    dontSpecifyOnThisChunk: {
      expectedTypeOnStCh: "boolean",
    },
    specificLemmas: {
      expectedTypeOnStCh: "array",
      ultimatelyMultipleTraitValuesOkay: true,
      traitValue: [],
    },
    specificIds: {
      expectedTypeOnStCh: "array",
      ultimatelyMultipleTraitValuesOkay: true,
      traitValue: [],
    },
    andTags: {
      expectedTypeOnStCh: "array",
      ultimatelyMultipleTraitValuesOkay: true,
      traitValue: ["colour"],
    },
    orTags: {
      expectedTypeOnStCh: "array",
      ultimatelyMultipleTraitValuesOkay: true,
      traitValue: [],
    },
    chunkId: {
      expectedTypeOnStCh: "string",
    },
    merelyPreferredChoicesForQuestionSentence: {
      expectedTypeOnStCh: "array",
    },
    agreeWith: {
      expectedTypeOnStCh: "string",
      mustBeExistingChunkId: true,
    },
    connectedTo: {
      expectedTypeOnStCh: "string",
      mustBeExistingChunkId: true,
    },
  },
};
